apiVersion: v1
kind: Secret
metadata:
  name: openai-secrets
type: Opaque
data:
  api-key: MXl1Z3UyN0JzWW5hN2dBTXBKU1ZMbkdKNjU1ME1zbWRRcE1PTTlyRXF4cVRxemxHdmNKYkpRUUo5OUJIQUNZZUJqRlhKM3czQUFBQkFDT0dwaE01
  endpoint: aHR0cHM6Ly9pbnNpZ2h0Zmxvdy1yZXNvdXJjZS5vcGVuYWkuYXp1cmUuY29tLw==
